apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: watermarkhorizontalpodautoscalers.whpa.datadoghq.com
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    name: age
    type: date
  - JSONPath: .spec.replicas
    name: replicas
    type: integer
  - JSONPath: .status.podReady
    name: ready
    type: integer
  group: whpa.datadoghq.com
  names:
    kind: WatermarkHorizontalPodAutoscaler
    listKind: WatermarkHorizontalPodAutoscalerList
    plural: watermarkhorizontalpodautoscalers
    singular: watermarkhorizontalpodautoscaler
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            replicas:
              format: int32
              type: integer
          type: object
        status:
          properties:
            podReady:
              format: int32
              type: integer
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
