apiVersion: apps/v1
kind: Deployment
metadata:
  name: whpa
spec:
  replicas: 1
  selector:
    matchLabels:
      name: whpa
  template:
    metadata:
      labels:
        name: whpa
    spec:
      serviceAccountName: whpa
      containers:
        - name: whpa
          # Replace this with the built image name
          image: whpa/controller:v0.0.1
          command:
          - whpa
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "whpa"
